# generated by datamodel-codegen:
#   filename:  bet.json

from __future__ import annotations

from typing import Any, Dict, Optional, Union

from pydantic import BaseModel, Field


class BetItem(BaseModel):
    against: Dict[str, Any]


class BetItem1(BaseModel):
    for_: Dict[str, Any] = Field(..., alias='for')


class BetParameter(BaseModel):
    bet: Union[BetItem, BetItem1]
    eventId: Optional[str]
    minimalWinAmount: str
