# generated by datamodel-codegen:
#   filename:  provideLiquidity.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ProvideLiquidityParameter(BaseModel):
    eventId: Optional[str]
    expectedRatioAgainst: str
    expectedRatioFor: str
    maxSlippage: str
