# generated by datamodel-codegen:
#   filename:  startMeasurementCallback.json

from __future__ import annotations

from pydantic import BaseModel


class StartMeasurementCallbackParameter(BaseModel):
    currencyPair: str
    lastUpdate: str
    rate: str
