# generated by datamodel-codegen:
#   filename:  withdraw.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class WithdrawParameter(BaseModel):
    __root__: Optional[str]
