# generated by datamodel-codegen:
#   filename:  oracleData_value.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class OracleDataValue(BaseModel):
    class Config:
        extra = Extra.forbid

    timestamp_0: str
    timestamp_1: str
    nat_0: str
    nat_1: str
    nat_2: str
    nat_3: str
    nat_4: str
