-- CREATE MATERIALIZED VIEW quotes_wma_15m WITH (timescaledb.continuous) AS
-- SELECT
--   avg(qw.price) as price,
--   public.time_bucket(INTERVAL '15 minutes', timestamp) AS bucket
-- FROM
--   juster.quotes_wma qw
-- GROUP BY
--   bucket;
