spec_version: 1.1
package: juster

database:
  kind: sqlite
  path: ":memory:"

contracts:
  coinbase_storage_mainnet:
    address: KT1Jr5t9UvGiqkvvsuUbPJHaYx24NzdUwNW9
    typename: harbinger_storage
  coinbase_storage_florencenet:
    address: KT1PuT2NwwNjnxKy5XZEDZGHQNgdtLgN69i9
    typename: harbinger_storage
  juster_florencenet:
    address: KT1CepDBrMg73d7LHm773KAsunjAjgLYituP
    typename: juster

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: https://api.tzkt.io
  tzkt_florencenet:
    kind: tzkt
    url: https://api.florencenet.tzkt.io
  coinbase:
    kind: coinbase

templates:
  harbinger_storage:
    kind: big_map
    datasource: <datasource>
    handlers:
      - callback: on_oracle_storage_update
        contract: <harbinger_storage>
        path: oracleData
    # NOTE: Jul 5, 1:27:36 AM on florencenet
    first_block: 318700

  juster:
    kind: operation
    datasource: <datasource>
    contracts:
      - <juster>
    handlers:
      - callback: on_new_event
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: newEvent
      - callback: on_provide_liquidity
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: provideLiquidity
      - callback: on_bet
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: bet
      - callback: on_start_measurement
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: startMeasurementCallback
          - type: transaction
            source: <juster>
      - callback: on_close
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: closeCallback
          - type: transaction
            source: <juster>
      - callback: on_withdraw
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: withdraw
          - type: transaction
            source: <juster>
          - type: transaction
            source: <juster>
            optional: True
      - callback: on_force_majeure
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: triggerForceMajeure
          - type: transaction
            source: <juster>

indexes:
  harbinger_florencenet:
    template: harbinger_storage
    values:
      datasource: tzkt_florencenet
      harbinger_storage: coinbase_storage_florencenet


jobs:
  coinbase_xtz_usd_1m_candles:
    callback: fetch_coinbase_candles
    crontab: "* * * * *"
    atomic: True
    args:
      datasource: coinbase
      currency_pair: XTZ-USD
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36

  coinbase_btc_usd_1m_candles:
    callback: fetch_coinbase_candles
    crontab: "* * * * *"
    atomic: True
    args:
      datasource: coinbase
      currency_pair: BTC-USD
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
