spec_version: 1.1
package: juster

database:
  kind: sqlite
  path: ":memory:"

contracts:
  coinbase_storage_mainnet:
    address: KT1Jr5t9UvGiqkvvsuUbPJHaYx24NzdUwNW9
    typename: harbinger_storage
  coinbase_storage_florencenet:
    address: KT1PuT2NwwNjnxKy5XZEDZGHQNgdtLgN69i9
    typename: harbinger_storage
  coinbase_storage_granadanet:
    address: KT1MwuujtBodVQFm1Jk1KTGNc49wygqoLvpe
    typename: harbinger_storage
  juster_florencenet:
    address: KT1CepDBrMg73d7LHm773KAsunjAjgLYituP
    typename: juster
  juster_granadanet:
    address: KT1T1w1E2iMyQpogneqR2552pvrEpF7AZ8kL
    typename: juster

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: https://api.tzkt.io
  tzkt_florencenet:
    kind: tzkt
    url: https://api.florencenet.tzkt.io
  tzkt_granadanet:
    kind: tzkt
    url: https://api.granadanet.tzkt.io
  coinbase:
    kind: coinbase

templates:
  harbinger_storage:
    kind: big_map
    datasource: <datasource>
    handlers:
      - callback: on_oracle_storage_update
        contract: <harbinger_storage>
        path: oracleData

  juster:
    kind: operation
    datasource: <datasource>
    contracts:
      - <juster_contract>
    handlers:
      - callback: on_new_event
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: newEvent
      - callback: on_provide_liquidity
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: provideLiquidity
      - callback: on_bet
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: bet
      - callback: on_start_measurement
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: startMeasurementCallback
          - type: transaction
            source: <juster_contract>
      - callback: on_close
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: closeCallback
          - type: transaction
            source: <juster_contract>
      - callback: on_withdraw
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: withdraw
          - type: transaction
            source: <juster_contract>
            optional: True
          - type: transaction
            source: <juster_contract>
            optional: True
      - callback: on_force_majeure
        pattern:
          - type: transaction
            destination: <juster_contract>
            entrypoint: triggerForceMajeure
          - type: transaction
            source: <juster_contract>

indexes:
  # harbinger_florencenet:
  #   template: harbinger_storage
  #   values:
  #     datasource: tzkt_florencenet
  #     harbinger_storage: coinbase_storage_florencenet
  harbinger_granadanet:
    template: harbinger_storage
    values:
      datasource: tzkt_granadanet
      harbinger_storage: coinbase_storage_granadanet
  # juster_florencenet:
  #   template: juster
  #   values:
  #     datasource: tzkt_florencenet
  #     juster_contract: juster_florencenet
  juster_granadanet:
    template: juster
    values:
      datasource: tzkt_granadanet
      juster_contract: juster_granadanet

jobs:
  coinbase_xtz_usd_1m_candles:
    callback: fetch_coinbase_candles
    crontab: "* * * * *"
    atomic: True
    args:
      datasource: coinbase
      currency_pair: XTZ-USD
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
  coinbase_btc_usd_1m_candles:
    callback: fetch_coinbase_candles
    crontab: "* * * * *"
    atomic: True
    args:
      datasource: coinbase
      currency_pair: BTC-USD
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
  coinbase_eth_usd_1m_candles:
    callback: fetch_coinbase_candles
    crontab: "* * * * *"
    atomic: True
    args:
      datasource: coinbase
      currency_pair: ETH-USD
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
