spec_version: 1.2
package: juster

database:
  kind: sqlite
  path: ":memory:"

contracts:
  coinbase_storage_mainnet:
    address: KT1Jr5t9UvGiqkvvsuUbPJHaYx24NzdUwNW9
    typename: harbinger_storage
  coinbase_storage_florencenet:
    address: KT1PuT2NwwNjnxKy5XZEDZGHQNgdtLgN69i9
    typename: harbinger_storage
  coinbase_storage_granadanet:
    address: KT1ENR6CK7cBWCtZt1G3PovwTw3FgSW472mS
    typename: harbinger_storage
  juster_florencenet:
    address: KT1CepDBrMg73d7LHm773KAsunjAjgLYituP
    typename: juster
  juster_granadanet:
    address: KT1JPehwEkAhg1z5RVA8wAccYbDgF2E2itDv
    typename: juster

datasources:
#  tzkt_mainnet:
#    kind: tzkt
#    url: https://api.tzkt.io
#  tzkt_florencenet:
#    kind: tzkt
#    url: https://api.florencenet.tzkt.io
  tzkt_granadanet:
    kind: tzkt
    url: https://api.granadanet.tzkt.io
  coinbase:
    kind: coinbase

templates:
  harbinger:
    kind: big_map
    datasource: <datasource>
#    first_level: 318700
    handlers:
      - callback: on_oracle_storage_update
        contract: <contract>
        path: oracleData

  juster:
    kind: operation
    datasource: <datasource>
    contracts:
      - <contract>
    handlers:
      - callback: on_new_event
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: newEvent
      - callback: on_provide_liquidity
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: provideLiquidity
      - callback: on_bet
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: bet
      - callback: on_start_measurement
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: startMeasurementCallback
          - type: transaction
            source: <contract>
      - callback: on_close
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: closeCallback
          - type: transaction
            source: <contract>
      - callback: on_withdraw
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: withdraw
          - type: transaction
            source: <contract>
            optional: True
          - type: transaction
            source: <contract>
            optional: True
      - callback: on_force_majeure
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: triggerForceMajeure
          - type: transaction
            source: <contract>

indexes:
#  harbinger_florencenet:
#    template: harbinger
#    values:
#      datasource: tzkt_florencenet
#      contract: coinbase_storage_florencenet
#  juster_florencenet:
#    template: juster
#    values:
#      datasource: tzkt_florencenet
#      contract: juster_florencenet
  harbinger_granadanet:
    template: harbinger
    values:
      datasource: tzkt_granadanet
      contract: coinbase_storage_granadanet
  juster_granadanet:
    template: juster
    values:
      datasource: tzkt_granadanet
      contract: juster_granadanet

hooks:
  fetch_coinbase_candles:
    callback: fetch_coinbase_candles
    atomic: false
    args:
      datasource: str
      candle_interval: str
      since: str
      currency_pair: str
  refresh_views:
    callback: refresh_views
    atomic: false

jobs:
  coinbase_xtz_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
      currency_pair: XTZ-USD
  coinbase_btc_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
      currency_pair: BTC-USD
  coinbase_eth_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: 2021-07-05T01:27:36
      currency_pair: ETH-USD
  refresh_views:
    hook: refresh_views
    crontab: "* * * * *"
