spec_version: 1.2
package: juster

database:
  kind: postgres
  host: db
  port: 5432
  user: ${POSTGRES_USER:-dipdup}
  password: ${POSTGRES_PASSWORD:-changeme}
  database: ${POSTGRES_DB:-dipdup}

hasura:
  url: http://hasura:8080
  admin_secret: ${ADMIN_SECRET:-changeme}
  select_limit: ${SELECT_LIMIT:-1000}
  camel_case: true
  allow_aggregations: false
  rest: true

contracts:
  coinbase_storage_hangzhounet:
    address: KT19yapgDLPR3CuvK32xJHgxNJigyNxjSr4y
    typename: harbinger_storage
  juster_hangzhounet:
    address: KT197iHRJaAGw3oGpQj21YYV1vK9Fa5ShoMn
    typename: juster

datasources:
  tzkt_hangzhounet:
    kind: tzkt
    url: https://api.hangzhou2net.tzkt.io
  coinbase:
    kind: coinbase
    http:
      cache: False

templates:
  harbinger:
    kind: big_map
    datasource: <datasource>
    handlers:
      - callback: on_oracle_storage_update
        contract: <contract>
        path: oracleData

  juster:
    kind: operation
    datasource: <datasource>
    contracts:
      - <contract>
    handlers:
      - callback: on_new_event
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: newEvent
      - callback: on_provide_liquidity
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: provideLiquidity
      - callback: on_bet
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: bet
      - callback: on_start_measurement
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: startMeasurementCallback
          - type: transaction
            source: <contract>
      - callback: on_close
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: closeCallback
          - type: transaction
            source: <contract>
      - callback: on_withdraw
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: withdraw
          - type: transaction
            source: <contract>
            optional: True
          - type: transaction
            source: <contract>
            optional: True
      - callback: on_force_majeure
        pattern:
          - type: transaction
            destination: <contract>
            entrypoint: triggerForceMajeure
          - type: transaction
            source: <contract>

indexes:
  harbinger_hangzhounet:
    template: harbinger
    values:
      datasource: tzkt_hangzhounet
      contract: coinbase_storage_hangzhounet
  juster_hangzhounet:
    template: juster
    values:
      datasource: tzkt_hangzhounet
      contract: juster_hangzhounet

hooks:
  fetch_coinbase_candles:
    callback: fetch_coinbase_candles
    atomic: false
    args:
      datasource: str
      candle_interval: str
      since: str
      currency_pair: str
  refresh_views:
    callback: refresh_views
    atomic: false

jobs:
  coinbase_xtz_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: ${CANDLES_SINCE:-2022-01-01T00:00:00}
      currency_pair: XTZ-USD
  coinbase_btc_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: ${CANDLES_SINCE:-2022-01-01T00:00:00}
      currency_pair: BTC-USD
  coinbase_eth_usd_1m_candles:
    hook: fetch_coinbase_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      candle_interval: ONE_MINUTE
      since: ${CANDLES_SINCE:-2022-01-01T00:00:00}
      currency_pair: ETH-USD
  refresh_views:
    hook: refresh_views
    crontab: "* * * * *"
