spec_version: 1.0
package: juster

database:
  kind: sqlite
  path: juster.sqlite3

contracts:
  coinbase_storage_mainnet:
    address: KT1Jr5t9UvGiqkvvsuUbPJHaYx24NzdUwNW9
    typename: harbinger_storage
  coinbase_normalizer_mainnet:
    address: KT1AdbYiPYb5hDuEuVrfxmFehtnBCXv4Np7r
    typename: harbinger_normalizer
  harbinger_normalizer_florencenet:
    address: KT1SUP27JhX24Kvr11oUdWswk7FnCW78ZyUn
    typename: harbinger_normalizer
  juster_florencenet:
    address: KT1CepDBrMg73d7LHm773KAsunjAjgLYituP
    typename: juster

datasources:
  tzkt_mainnet:
    kind: tzkt
    url: https://api.tzkt.io
  tzkt_florencenet:
    kind: tzkt
    url: https://api.florencenet.tzkt.io
  coinbase:
    kind: coinbase

templates:
  harbinger_normalizer:
    kind: big_map
    datasource: <datasource>
    handlers:
      - callback: on_oracle_update
        contract: <harbinger_normalizer>
        path: assetMap
    # NOTE: 28 jun on florence
    first_block: 302700

  juster:
    kind: operation
    datasource: <datasource>
    contracts:
      - <juster>
    handlers:
      - callback: on_new_event
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: newEvent
      - callback: on_provide_liquidity
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: provideLiquidity
      - callback: on_bet
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: bet
      - callback: on_start_measurement
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: startMeasurementCallback
          - type: transaction
            source: <juster>
      - callback: on_close
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: closeCallback
          - type: transaction
            source: <juster>
      - callback: on_withdraw
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: withdraw
          - type: transaction
            source: <juster>
          - type: transaction
            source: <juster>
            optional: True
      - callback: on_force_majeure
        pattern:
          - type: transaction
            destination: <juster>
            entrypoint: triggerForceMajeure
          - type: transaction
            source: <juster>

indexes:
  # harbinger_mainnet:
  #   template: harbinger_normalizer
  #   values:
  #     datasource: tzkt_staging_mainnet
  #     normalizer: coinbase_normalizer_mainnet

  harbinger_florencenet:
    template: harbinger_normalizer
    values:
      datasource: tzkt_florencenet
      harbinger_normalizer: harbinger_normalizer_florencenet

  juster_florencenet:
    template: juster
    values:
      datasource: tzkt_florencenet
      juster: juster_florencenet

jobs:
  minute_candles_xtz:
    callback: fetch_candles
    crontab: "* * * * *"
    args:
      datasource: coinbase
      currency_pair: XTZ-USD
      candle_interval: ONE_MINUTE
      since: 2021-06-29T00:00:00
      points: 7
