[tool.poetry]
name = "baking-bet"
version = "0.0.1"
description = ""
authors = ["Lev Gorodetskiy <github@droserasprout.space>"]

[tool.poetry.dependencies]
python = "^3.9"
dipdup = {git = "https://github.com/dipdup-net/dipdup-py.git"}
dateutils = "^0.6.12"

[tool.poetry.dev-dependencies]
mypy = "^0.812"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
