[tool.poetry]
name = "juster-dipdup"
version = "0.0.1"
description = ""
authors = ["Lev Gorodetskiy <github@droserasprout.space>"]

[tool.poetry.dependencies]
python = "^3.8"
dipdup = "3.1.1"
strict-rfc3339 = "^0.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
bump2version = "^1.0.1"
diff-cover = "^5.0.1"
isort = "^5.7.0"
mypy = "^0.812"
pytest = "^3.0"
pytest-cov = "^2.4"
flake8 = "3.9.0"
flakehell = "^0.9.0"

[tool.isort]
line_length = 140

[tool.black]
line-length = 140
target-version = ['py38']
skip-string-normalization = true

[tool.flakehell]
format = "colored"
max_line_length = 140
show_source = true

[tool.flakehell.plugins]
pyflakes = ["+*"]
"flake8-*" = ["+*"]
flake8-docstrings = ["-*"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
