[tool.poetry]
name = "juster-dipdup"
version = "0.0.1"
description = ""
authors = ["Lev Gorodetskiy <github@droserasprout.space>"]

[tool.poetry.dependencies]
python = "^3.8"
# dipdup = {git = "https://github.com/dipdup-net/dipdup-py.git", branch = "feat/coinbase-datasource"}
dipdup = {path = "../dipdup", develop = true }

[tool.poetry.dev-dependencies]
mypy = "^0.812"
matplotlib = "^3.4.2"
notebook = "^6.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
