# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel


class Key(BaseModel):
    address: str
    nat: str


class BetsAboveEqItem(BaseModel):
    key: Key
    value: str


class Key1(BaseModel):
    address: str
    nat: str


class BetsBellowItem(BaseModel):
    key: Key1
    value: str


class Key2(BaseModel):
    address: str
    nat: str


class DepositedBet(BaseModel):
    key: Key2
    value: str


class Events(BaseModel):
    betsCloseTime: str
    closedDynamics: str
    closedOracleTime: str
    closedRate: str
    createdTime: str
    currencyPair: str
    expirationFee: str
    isBetsAboveEqWin: bool
    isClosed: bool
    isForceMajeure: bool
    isMeasurementStarted: bool
    liquidityPercent: str
    maxAllowedMeasureLag: str
    measureOracleStartTime: str
    measurePeriod: str
    measureStartFee: str
    oracleAddress: str
    poolAboveEq: str
    poolBellow: str
    rewardCallFee: str
    startRate: str
    targetDynamics: str
    totalLiquidityShares: str


class Key3(BaseModel):
    address: str
    nat: str


class LiquidityShare(BaseModel):
    key: Key3
    value: str


class NewEventConfig(BaseModel):
    defaultTime: str
    expirationFee: str
    maxAllowedMeasureLag: str
    maxLiquidityPercent: str
    maxMeasurePeriod: str
    maxPeriodToBetsClose: str
    measureStartFee: str
    minLiquidityPercent: str
    minMeasurePeriod: str
    minPeriodToBetsClose: str
    oracleAddress: str
    rewardCallFee: str


class Key4(BaseModel):
    address: str
    nat: str


class ProvidedLiquidityAboveEqItem(BaseModel):
    key: Key4
    value: str


class Key5(BaseModel):
    address: str
    nat: str


class ProvidedLiquidityBellowItem(BaseModel):
    key: Key5
    value: str


class BetsStorage(BaseModel):
    betsAboveEq: List[BetsAboveEqItem]
    betsBellow: List[BetsBellowItem]
    closeCallId: Optional[str]
    depositedBets: List[DepositedBet]
    events: Dict[str, Events]
    lastEventId: str
    liquidityPrecision: str
    liquidityShares: List[LiquidityShare]
    manager: str
    measurementStartCallId: Optional[str]
    newEventConfig: NewEventConfig
    providedLiquidityAboveEq: List[ProvidedLiquidityAboveEqItem]
    providedLiquidityBellow: List[ProvidedLiquidityBellowItem]
    ratioPrecision: str
    sharePrecision: str
    targetDynamicsPrecision: str
