# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class DefaultParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    push: str


class DefaultParameterItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    revoke: str


class Update(BaseModel):
    class Config:
        extra = Extra.forbid

    signature: str
    timestamp_0: str
    timestamp_1: str
    nat_0: str
    nat_1: str
    nat_2: str
    nat_3: str
    nat_4: str


class DefaultParameterItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    update: Dict[str, Update]


class DefaultParameter(BaseModel):
    __root__: Union[DefaultParameterItem, DefaultParameterItem1, DefaultParameterItem2]
