# generated by datamodel-codegen:
#   filename:  assetMap.value.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Prices(BaseModel):
    first: str
    last: str
    saved: Dict[str, str]
    sum: str


class Volumes(BaseModel):
    first: str
    last: str
    saved: Dict[str, str]
    sum: str


class AssetMapValue(BaseModel):
    computedPrice: str
    lastUpdateTime: str
    prices: Prices
    volumes: Volumes
