# generated by datamodel-codegen:
#   filename:  addLine.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class AddLineParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    advanceTime: str
    betsPeriod: str
    currencyPair: str
    isPaused: bool
    juster: str
    lastBetsCloseTime: str
    liquidityPercent: str
    maxEvents: str
    measurePeriod: str
    minBettingPeriod: str
    rateAboveEq: str
    rateBelow: str
    targetDynamics: str
