# generated by datamodel-codegen:
#   filename:  disband.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class DisbandParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
