# generated by datamodel-codegen:
#   filename:  setEntryLockPeriod.json

from __future__ import annotations

from pydantic import BaseModel


class SetEntryLockPeriodParameter(BaseModel):
    __root__: str
