# generated by datamodel-codegen:
#   filename:  triggerPauseLine.json

from __future__ import annotations

from pydantic import BaseModel


class TriggerPauseLineParameter(BaseModel):
    __root__: str
