# generated by datamodel-codegen:
#   filename:  close.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class CloseParameter(BaseModel):
    __root__: Optional[str]
