# generated by datamodel-codegen:
#   filename:  closeCallback.json

from __future__ import annotations

from pydantic import BaseModel


class CloseCallbackParameter(BaseModel):
    currencyPair: str
    lastUpdate: str
    rate: str
