# generated by datamodel-codegen:
#   filename:  startMeasurement.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class StartMeasurementParameter(BaseModel):
    __root__: Optional[str]
