# generated by datamodel-codegen:
#   filename:  withdraw.json

from __future__ import annotations

from pydantic import BaseModel


class WithdrawParameter(BaseModel):
    eventId: str
    participantAddress: str
