# generated by datamodel-codegen:
#   filename:  bet.json

from __future__ import annotations

from typing import Any, Dict, Union

from pydantic import BaseModel


class BetItem(BaseModel):
    aboveEq: Dict[str, Any]


class BetItem1(BaseModel):
    below: Dict[str, Any]


class BetParameter(BaseModel):
    bet: Union[BetItem, BetItem1]
    eventId: str
    minimalWinAmount: str
