# generated by datamodel-codegen:
#   filename:  provideLiquidity.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class ProvideLiquidityParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    eventId: str
    expectedRatioAboveEq: str
    expectedRatioBelow: str
    maxSlippage: str
