# generated by datamodel-codegen:
#   filename:  triggerForceMajeure.json

from __future__ import annotations

from pydantic import BaseModel


class TriggerForceMajeureParameter(BaseModel):
    __root__: str
