# generated by datamodel-codegen:
#   filename:  approveLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class ApproveLiquidityParameter(BaseModel):
    __root__: str
