# generated by datamodel-codegen:
#   filename:  cancelLiquidity.json

from __future__ import annotations

from pydantic import BaseModel


class CancelLiquidityParameter(BaseModel):
    __root__: str
